baseurl: "" # the subpath of your site, e.g. blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com/

title: Simão.
description: >- # this means to ignore newlines until "baseurl:"
  José Pedro Schardosim Simão - Software Engineer

#################### Comment Section (Disqus) ################
disqus_shortname: "" # Add your shortname for Disqus Comment. For example : mr-brown


# Scss Directory
sass:
  sass_dir: assets/scss
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-multiple-languages-plugin

paginate: 6
paginate_path: "/blog/page:num/"

excerpt_separator: <!-- more -->

# include
include:
  - _pages
  - _authors

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

  - scope:
      path: "_authors"
    values:
      permalink: /author/:basename:output_ext
      layout: author

  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: post/:title:output_ext
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tags
tag_permalink_style: pretty

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

languages: ["pt", "en"]
defaultLang: pt
exclude_from_localizations: ["js", "images", "scss", "plugins"]
languageNames:
  en: "English"
  pt: "Português"