########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/", key: "header.home" }
    - { name: About, url: "/about", key: "header.about" }
    - { name: Resumé, url: "/resume", key: "header.resume" }
    - { name: Projects, url: "/projects", key: "header.projects" }
    - { name: Publications, url: "/publications", key: "header.publications" }
    - { name: Blog, url: "/blog", key: "header.blog" }

######################### Default Parameters ###########################
# meta data
author: "José Pedro Schardosim Simão"
description: "José Pedro Schardosim Simão is a software engineer specialized in designing and developing solutions for the Internet and educational technologies. Currently, he's working as a Tech Lead at HardFun."
google_analitycs_id: "433541369" 

############################## Social Site ##########################
social:

  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/simaoj"

  - name: "linkedin"
    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link: "https://www.linkedin.com/in/jpsimao/
    "
  - name: "instagram"
    icon: "ti-instagram" # themify icon pack https://themify.me/themify-icons
    link: "https://www.instagram.com/simaoj_/"